### ISSUE TITLE
complex_to_real isn't working with boost::multiprecision::complex128

### ISSUE THREAD

**Issue by cosurgi** [BoostGSoC21/math#18]
When working on https://github.com/BoostGSoC21/math/pull/17 I encountered a problem that `boost::multiprecision::complex128` isn't working in [fft_ex_06.cpp](https://github.com/BoostGSoC21/math/blob/fft_janek/example/fft_ex06.cpp#L104).

Before changes in https://github.com/BoostGSoC21/math/pull/17 it was using `std::complex<boost::multiprecision::float128>` and worked.

Let's us track here progress with this problem.

@Lagrang3 @ckormanyos , any ideas?

**Comment by Lagrang3** [comment]
We have two versions of this [example](https://github.com/BoostGSoC21/math/blob/ex06-float128/example/fft_ex06.cpp), one with builtin types that we can test without multiprecision dependencies and [another](https://github.com/BoostGSoC21/math/blob/ex06-float128/example/fft_ex06_float128.cpp) version for float128. Unfortunately the complex type cannot be deduce yet and `std::complex<boost::multiprecision::float128>` is undefined according to the standard.

Nevertheless, the example works. I think we can close this issue. The complex selection is already a subject in the discussion #16.

**Comment by Lagrang3** [comment]
Sorry. We'll close it if we merge #31.

**Comment by cosurgi** [comment]
Yes. I agree, thank you! :)
