### ISSUE TITLE
Set up a simple project specific CI for FFT only

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/math#2]
Deactivate the _normal_ Math CI in this fork and set up a simple project specific CI for FFT only.

**Comment by ckormanyos** [comment]
Hi @Lagrang3 and @cosurgi I have set up a realy minimalistic attempt at some CI running GCC/clang for the few files in the Jam in Eduardos preliminary work.

CI is a rather big failure right now [as seen here](https://github.com/BoostGSoC21/math/actions).

Some of the errors look easy, such as not finding a particular `benchmark` header file. i might have made some simple mistakes, and probably did. But can you guys see any way to improve the preliminary CI? or see what if anything I forgot?

**Comment by ckormanyos** [comment]
Hi @Lagrang3 and @cosurgi also I should mention in order to get the CI draft you need to merge from the `fft_chris` branch. I did this into the `fft` barnch but only performed this merge for the `fft` branch.

**Comment by ckormanyos** [comment]
Hi @Lagrang3 and @cosurgi sorry for so many posts.

This [preliminary simple CI](https://github.com/BoostGSoC21/math/actions/runs/964657625) has _gone green_. I needed to remember that clang does not have support for libquadmath. Also I needed to remember to compile with -std_gnu++11, 14, 17, 2a in order to activate the non-standard quadmath on GCC.

One problem remains for, maybe, later. I removed the benchmark test from bjam since the header could not be found. If this gets restored, then CI is good to go.

I found a few places needing to be patched for traditional C++11. These are now in CI, so we will detect future breakages there.

Good job guys on a strong start.

**Comment by ckormanyos** [comment]
Fixed by 94b34322a7b46f8b5e04804d6061728a321a7a7a

**Comment by cosurgi** [comment]
Thank you. I managed to bring back clang to CI, but had to open https://github.com/BoostGSoC21/math/issues/4

**Comment by ckormanyos** [comment]
CI in itself for FFT only is working.

Compiler/Domain-specific problems will be handled within their separate issues.
